package com.sgu.infowksporga.business.xml.jaxb.preference;

import java.io.Serializable;

import com.sgu.infowksporga.business.xml.jaxb.perspective.XmlPreference;

/**
 * Description : AbstractXmlPreferencesTreeTag class<br>
 */
public abstract class AbstractXmlPreferenceTemplateTag implements Serializable {

  /**
   * The attribute serialVersionUID
   */
  private static final long serialVersionUID = 4267287082052706725L;

  /**
   * The parent for this element
   */
  private AbstractXmlPreferenceTemplateTag parent;

  /**
   * Constructor<br>
   */
  public AbstractXmlPreferenceTemplateTag() {

  }

  /**
   * @see #parent
   * @return the parent : See field description
   */
  public AbstractXmlPreferenceTemplateTag getParent() {
    return parent;
  }

  /**
   * @see #parent
   * @param parent : See field description
   */
  public void setParent(final AbstractXmlPreferenceTemplateTag parent) {
    this.parent = parent;
  }

  /**
   * {@inheritDoc}
   */
  public XmlPreference getXmlPreference() {
    return new XmlPreference();
  }

  /**
   * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
   * @overwrite toString()
   * @return String returns this object in a String
   */
  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("[ parent:=");
    sb.append(parent.getClass().getName());
    sb.append(']');
    return sb.toString();
  }

}
