package com.sgu.infowksporga.jfx.views.file.explorer.tree;

import java.io.File;

import javax.swing.Icon;

import com.sgu.core.framework.pivot.AbstractOut;
import com.sgu.core.framework.util.Util;

/**
 * Description : FileVo class<br>
 *
 */
public class FileVo extends AbstractOut {

  /**
   * The attribute serialVersionUID
   */
  private static final long serialVersionUID = -8199187116867698936L;

  /**
   * Store the file
   */
  private File file;

  /**
   * Store the icon of the file
   */
  private Icon fileIcon;

  /**
   * Store the size of the file
   */
  private String fileSize;

  /**
   * Store the last modified date of the file
   */
  private String lastModifiedDate;

  /**
   * Constructor<br>
   *
   */
  public FileVo() {
    super();
  }

  /**
   * @see #file
   * @return the file : See field description
   */
  public File getFile() {
    return file;
  }

  /**
   * @see #file
   * @param file : See field description
   */
  public void setFile(final File file) {
    this.file = file;
  }

  /**
   * @see #fileIcon
   * @return the fileIcon : See field description
   */
  public Icon getFileIcon() {
    return fileIcon;
  }

  /**
   * @see #fileIcon
   * @param fileIcon : See field description
   */
  public void setFileIcon(final Icon fileIcon) {
    this.fileIcon = fileIcon;
  }

  /**
   * @see #fileSize
   * @return the fileSize : See field description
   */
  public String getFileSize() {
    return fileSize;
  }

  /**
   * @see #fileSize
   * @param fileSize : See field description
   */
  public void setFileSize(final String fileSize) {
    this.fileSize = fileSize;
  }

  /**
   * @see #lastModifiedDate
   * @return the lastModifiedDate : See field description
   */
  public String getLastModifiedDate() {
    return lastModifiedDate;
  }

  /**
   * @see #lastModifiedDate
   * @param lastModifiedDate : See field description
   */
  public void setLastModifiedDate(final String lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /**
   * 
   * {@inheritDoc}
   */
  @Override
  public boolean equals(final Object obj) {
    boolean result = false;
    if (obj != null) {
      result = Util.isEqual(this.getFile(), ((FileVo) obj).getFile());
    } else {
      result = Util.isEqual(this, null);
    }

    return result;
  }

  /**
  * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
  * @overwrite hashCode()
  * @return int the Objects hashcode.
  */
  @Override
  public int hashCode() {// NOPMD
    int hashCode = super.hashCode();
    hashCode = 31 * hashCode + (int) (+serialVersionUID ^ (serialVersionUID >>> 32));
    hashCode = 31 * hashCode + (file == null ? 0 : file.hashCode());
    return hashCode;
  }

  /**
  * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
  * @overwrite toString()
  * @return String returns this object in a String
  */
  @Override
  public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("FileVo[");
    sb.append(" file:=");
    sb.append(file);
    sb.append(']');
    return sb.toString();
  }

}
