-- Utilisateur administrateur pour pouvoir importer les fichiers utilisateur, projets & affectations 
Insert into USERS (LOGIN,SURNAME,NAME,PASSWORD,EMAIL_1,EMAIL_2) values ('admin','GUISSE','Sébastien','xZVXPC','sebastien.guisse@gfi.fr','sebastien.guisse@externe.bnpparibas.com');

-- Insert la ligne necessaire pour pouvoir definir le workspace accessible quand on clique sur un item de projet ou TMA (ici BNPP)
-- Vue commune à tous les projets BNPP ou TMA BNPP
INSERT INTO workspace (CODE, PROJECT_CODE, TYPE, WKS_ORDER, LAYOUT, VISIBILITY, USERCRE, DATCRE, USERMAJ, DATMAJ) VALUES ('PROJECT','ALL_PROJECT_BNPP','PROJECT',0,null,'PUBLIC','sguisse','2013-02-15 06:37:23',NULL,NULL);
INSERT INTO workspace (CODE, PROJECT_CODE, TYPE, WKS_ORDER, LAYOUT, VISIBILITY, USERCRE, DATCRE, USERMAJ, DATMAJ) VALUES ('PROJECT','ALL_TMA_BNPP','PROJECT',0,null,'PUBLIC','sguisse','2013-02-15 06:37:23',NULL,NULL);

INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('GENERAL','Fichier-indicateurs-anomalies-BNPP','A définir','DEFAULT',1);

INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','651-BNPP','/01. Documentation transmise par BNPP/03. 651','Documentation BNPP',22);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Chrono-BNPP','/01. Documentation transmise par BNPP/05. Chrono','Documentation BNPP',24);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Chrono-GFI','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant/00. Chrono','Documentation GFI',35);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','CMM-Harmonie','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant','Documentation GFI',34);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Contacts','/00. Suivi de projet/99. Contact','Suivi',15);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Contrat','/00. Suivi de projet/07. Contrat','Suivi',11);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','CR-Réunion','/00. Suivi de projet/00. Comptes-Rendu Réunion','Suivi',1);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','DEI','/05. Dei','DEI',41);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dessin-Chaines','/04. Dessin de chaines','Chaines',40);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Devis','/00. Suivi de projet/04. Devis','Suivi',8);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Documentation-BNPP','/01. Documentation transmise par BNPP','Documentation BNPP',16);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Documentation-GFI','/02. Documentation CSB','Documentation GFI',26);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossier-Présentation','/07. Etude TP et SGBD Grands systèmes/05. Dossier Présentation (ETE)','EtudeTP et SGBD',47);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossier-Validation','/08. Dossier de validation','Dossier de Validation',48);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossiers-SFD-BNPP','/01. Documentation transmise par BNPP/02. Dossiers SFD','Documentation BNPP',21);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossiers-SFD-GFI','/02. Documentation CSB/01. Dossiers SFD','Documentation GFI',28);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossiers-SFG-BNPP','/01. Documentation transmise par BNPP/01. Dossiers SFG','Documentation BNPP',20);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossiers-SFG-GFI','/02. Documentation CSB/00. Dossiers SFG','Documentation GFI',27);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Dossiers-SO','/02. Documentation CSB/03. Dossiers SO','Documentation GFI',29);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','EBD-Liste-Exigences','/01. Documentation transmise par BNPP/00. EDB liste exigences','Documentation BNPP',17);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','EDB','/01. Documentation transmise par BNPP/00. EDB liste exigences/00. EDB','Documentation BNPP',18);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Etude-TP-SGBD-GS','/07. Etude TP et SGBD Grands systèmes','EtudeTP et SGBD',42);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Exigences','/01. Documentation transmise par BNPP/00. EDB liste exigences/01. Exigences-Cas Utilisation','Documentation BNPP',19);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Faits-Marquants','/00. Suivi de projet/05. Faits marquants','Suivi',9);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Fiche-PAQ','/07. Etude TP et SGBD Grands systèmes/04. Fiche PAQ','EtudeTP et SGBD',46);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Fiches-Risques','/00. Suivi de projet/03. Fiches (Risques; Projet)','Suivi',4);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Fiches-Risques-Avant-Vente','/00. Suivi de projet/03. Fiches (Risques; Projet)/00. Avant-vente','Suivi',5);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Fiches-Risques-externe','/00. Suivi de projet/03. Fiches (Risques; Projet)/01. Fiches de risque externe','Suivi',6);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Fiches-Risques-interne','/00. Suivi de projet/03. Fiches (Risques; Projet)/02. Fiches de risque interne','Suivi',7);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Indicateurs','/00. Suivi de projet/10. Mesures des indicateurs','Suivi',13);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Liste-Questions-Réponses-BNPP','/01. Documentation transmise par BNPP/04. LQR','Documentation BNPP',23);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Modele-logique','/07. Etude TP et SGBD Grands systèmes/01. Modèle logique','EtudeTP et SGBD',43);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','PAQ','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant/03. AQ ST','Documentation GFI',38);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','PDL','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant/01. PDL','Documentation GFI',36);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','PGC','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant/02. GCL ST','Documentation GFI',37);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Phase-Qualification','/00. Suivi de projet/02. Suivi Phase de Qualification','Suivi',3);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Phase-Realisation','/00. Suivi de projet/01. Suivi Phase de Réalisation','Suivi',2);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Plan-Recette-GFI','/02. Documentation CSB/04. Plan de Recette Interne','Documentation GFI',31);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Planning-RAF','/00. Suivi de projet/08. Planning, RAF','Suivi',12);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Profil-Batch','/07. Etude TP et SGBD Grands systèmes/02. Profil batch','EtudeTP et SGBD',44);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','PV-Recette','/01. Documentation transmise par BNPP/06. PV de Recette','Documentation BNPP',25);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Rapport-Performance','/02. Documentation CSB/07. Documents CMM-Harmonie du sous-traitant/04. Rapport de performance','Documentation GFI',39);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Rapports-Flash','/00. Suivi de projet/06. Rapport Flash','Suivi',10);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Simulation-QCF','/07. Etude TP et SGBD Grands systèmes/03. Simulation QCF','EtudeTP et SGBD',45);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Suivi-de-projet','/00. Suivi de projet','Suivi',0);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Suivi-Livraisons','/02. Documentation CSB/05. Suivi des livraisons','Documentation GFI',32);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','System-Code','/02. Documentation CSB/06. SYSTEM-CODE','Documentation GFI',33);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','UML','/02. Documentation CSB/03. Dossiers SO/01. UML','Documentation GFI',30);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('PROJECT_BNPP_DIRECTORY','Validations','/00. Suivi de projet/90. Validations','Suivi',14);

INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Actions','/00. Suivi/09. Actions','Suivi',12);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Anomalies','/00. Suivi/80. Anomalies','Suivi',16);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Archives Notes','/07. Archives NOTES de la TMA','Archives',34);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','ASU - Travaux Récurrents','/03. Assistance utilisateurs - Travaux récurrents','Assistance Utilisateurs- Travaux Récurrents',24);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Base de connaissances','/01. Base de connaissances','Base de Connaissances',18);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Bilan annuel ST','/05. Harmonie sous-traitant/05. Bilan annuel ST','Harmonie',32);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Budget','/00. Suivi/06. Budget','Suivi',6);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Chrono','/05. Harmonie sous-traitant/00. Chrono','Harmonie',27);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Contacts','/01. Base de connaissances/00. Contacts','Base de Connaissances',19);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Contrats','/00. Suivi/05. Contrats','Suivi',5);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','CR-Rapport Activité ST','/00. Suivi/02. Rapports d\'activité ST','Suivi',2);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Documentation transverse','/01. Base de connaissances/99. Documentation transverse','Base de Connaissances',22);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Evolutions - Travaux Ponctuels','/02. Evolutions - Travaux ponctuels','Evolutions - Travaux Ponctuels',23);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Harmonie ST','/05. Harmonie sous-traitant','Harmonie',26);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Indicateurs','/00. Suivi/03. Indicateurs','Suivi',3);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Listes CMM','/06. Listes CMM','Listes CMM',33);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Maintenances techniques - Incidents','/04. Maintenances techniques - Incidents','Maintenances Techniques - Incidents',25);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','ODJ-Rapport Activité ST','/00. Suivi/01. Ordres du jour - Rapport d\'activite ST','Suivi',1);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','PAQ ST','/05. Harmonie sous-traitant/03. AQ ST','Harmonie',30);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Périmètre 01','/01. Base de connaissances/01. Périmètre 1','Base de Connaissances',20);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Périmètre 02','/01. Base de connaissances/02. Périmètre 2','Base de Connaissances',21);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','PGC ST','/05. Harmonie sous-traitant/02. GCL ST','Harmonie',29);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Planning','/00. Suivi/04. Planning','Suivi',4);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','POM ST','/05. Harmonie sous-traitant/01. POM ST','Harmonie',28);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Rapport Flash','/00. Suivi/07. Rapport flash CSB','Suivi',7);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Rapport performance ST','/05. Harmonie sous-traitant/04. Rapport de performance ST','Harmonie',31);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Revues','/00. Suivi/10. Revues','Suivi',13);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Revues-AQ','/00. Suivi/10. Revues/00. AQ','Suivi',14);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Revues-GCL','/00. Suivi/10. Revues/01. GCL','Suivi',15);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Risques','/00. Suivi/08. Risques','Suivi',8);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Risques-Avant-Vente','/00. Suivi/08. Risques/00. Avant-vente','Suivi',9);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Risques-Externes','/00. Suivi/08. Risques/01. Fiches de risque externe','Suivi',10);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Risques-Internes','/00. Suivi/08. Risques/02. Fiches de risque interne','Suivi',11);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Suivi','/00. Suivi','Suivi',0);
INSERT INTO preferences (CODE, PROP_KEY, PROP_VALUE, PREF_GROUP, PREF_ORDER) VALUES ('TMA_BNPP_DIRECTORY','Validations','/00. Suivi/90. Validations','Suivi',17);
