//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 03:43:00 PM CET 
//


package com.sgu.infowksporga.business.xml.jaxb.cmmi.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sgu.infowksporga.business.xml.jaxb.cmmi.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fr_QNAME = new QName("", "fr");
    private final static QName _En_QNAME = new QName("", "en");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sgu.infowksporga.business.xml.jaxb.cmmi.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link Practice }
     * 
     */
    public Practice createPractice() {
        return new Practice();
    }

    /**
     * Create an instance of {@link IndirectQuestion }
     * 
     */
    public IndirectQuestion createIndirectQuestion() {
        return new IndirectQuestion();
    }

    /**
     * Create an instance of {@link DirectQuestion }
     * 
     */
    public DirectQuestion createDirectQuestion() {
        return new DirectQuestion();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Cmmi }
     * 
     */
    public Cmmi createCmmi() {
        return new Cmmi();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fr")
    public JAXBElement<String> createFr(String value) {
        return new JAXBElement<String>(_Fr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "en")
    public JAXBElement<String> createEn(String value) {
        return new JAXBElement<String>(_En_QNAME, String.class, null, value);
    }

}
