//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 02:27:18 PM CET 
//


package com.sgu.infowksporga.business.xml.jaxb.toolbar;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}separator"/>
 *         &lt;element ref="{}toolbarItem"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "separatorOrToolbarItem"
})
@XmlRootElement(name = "toolbar-application")
public class ToolbarApplication
    implements Serializable
{

    private final static long serialVersionUID = 12376L;
    @XmlElements({
        @XmlElement(name = "toolbarItem", type = ToolbarItem.class),
        @XmlElement(name = "separator", type = Separator.class)
    })
    protected List<Object> separatorOrToolbarItem;

    /**
     * Gets the value of the separatorOrToolbarItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the separatorOrToolbarItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeparatorOrToolbarItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ToolbarItem }
     * {@link Separator }
     * 
     * 
     */
    public List<Object> getSeparatorOrToolbarItem() {
        if (separatorOrToolbarItem == null) {
            separatorOrToolbarItem = new ArrayList<Object>();
        }
        return this.separatorOrToolbarItem;
    }

}
