package de.cismet.test.javafxbrowserinswing;

import java.awt.BorderLayout;
import net.infonode.docking.View;
import net.infonode.docking.util.DockingUtil;
import net.infonode.docking.util.ViewMap;

public class Frame extends javax.swing.JFrame {

    private WebViewPanel wbpBrowser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    // End of variables declaration//GEN-END:variables

    public Frame() {
        initComponents();

        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnLoadActionPerformed(evt);
                }
            });
        getContentPane().add(btnLoad, java.awt.BorderLayout.PAGE_START);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        wbpBrowser.load("http://www.heise.de");
    }//GEN-LAST:event_btnLoadActionPerformed

    public static void main(final String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new Frame().setVisible(true);
                }
            });
    }

    private void initComponents2() {
        wbpBrowser = new WebViewPanel();
        
        View[] views = new View[1];
        ViewMap viewMap = new ViewMap();
        
        views[0] = new View("Browser", null, wbpBrowser);
        //views[0].addListener(wbpBrowser);
        viewMap.addView(0, views[0]);
        
        add(DockingUtil.createRootWindow(viewMap, true), BorderLayout.CENTER);
        setSize(800, 600);
        pack();
    }
}
