package com.sgu.infowksporga.business.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.sgu.core.framework.dao.jpa.entity.LockedEntity;

/**
 * The persistent class for the lock database table.
 */
@Entity
@Table(name = "lock")
public class Lock extends LockedEntity<Integer> {
  private static final long serialVersionUID = 1L;

  @Id
  @GenericGenerator(name = "MySqlIdentifierGenerator", strategy = "com.sgu.core.framework.dao.mysql.MySqlIdentifierGenerator",
  parameters = { @Parameter(name = "tableName", value = "lock") })
  @GeneratedValue(generator = "MySqlIdentifierGenerator")
  private Integer id;

  public Lock() {
    super();
  }

  public Lock(final LockedEntity<Integer> lockedEntity) {
    super(lockedEntity);
  }

  /**
   * Clone.
   *
   * @return Object
   * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis) clone
   */
  @Override
  public Lock clone() {
    final Lock cloned = new Lock(this);
    return cloned;
  }

  /** {@inheritDoc} */
  @Override
  public Integer getId() {
    return id;
  }

  /** {@inheritDoc} */
  @Override
  public void setId(final Integer id) {
    this.id = id;
  }

}